# Generated by Django 4.1 on 2022-09-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Redcrude_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phonenumber',
            field=models.IntegerField(null=True),
        ),
    ]
