# Generated by Django 4.1 on 2022-09-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Redcrude_App', '0002_alter_customuser_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'user'), (2, 'teacher'), (3, 'trader'), (4, 'admin')], default=4, max_length=50),
        ),
    ]
