# Generated by Django 4.1 on 2022-09-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Redcrude_App', '0003_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'admin'), (2, 'teacher'), (3, 'trader'), (4, 'user')], default=1, max_length=50),
        ),
    ]
