# Generated by Django 4.1 on 2022-09-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Redcrude_App', '0007_alter_customuser_user_type_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='phonenumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trader',
            name='phonenumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='phonenumber',
            field=models.IntegerField(),
        ),
    ]
