# Generated by Django 4.1 on 2022-09-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Redcrude_App', '0008_alter_teacher_phonenumber_alter_trader_phonenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phonenumber',
            field=models.CharField(default='9874563210', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phonenumber',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='trader',
            name='phonenumber',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='users',
            name='phonenumber',
            field=models.CharField(max_length=10),
        ),
    ]
